name: medicine_reminder
description: "MINDER - Your smart medicine reminder companion."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  adoptive_calendar: ^0.2.0
  awesome_datetime_picker: ^0.1.1
  awesome_dialog: ^3.2.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_calendar_picker: ^2.2.3
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  fl_chart: ^0.69.0
  flutter_local_notifications: ^18.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_carousel_widget: ^3.1.0
  flutter_modular: ^6.3.4
  intl: 0.20.2
  meta: ^1.16.0
  mockito: ^5.4.6
  path: ^1.9.1
  percent_indicator: ^4.2.4
  popup_menu_plus: ^0.0.6
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  wheel_picker: ^0.2.1
  mocktail: ^1.0.4
  build_runner: ^2.8.0
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
